### ISSUE TITLE
CartUpdate : setCustomType fail, need guidance to use it

### ISSUE THREAD

**Issue by NicolasREY69330** [commercetools/commercetools-dotnet-core-sdk-v2#171]
Hi,

I need to update a custom field on cart entity.
I created the field this way, it works as expected
```
curl --location --request POST 'https://api.europe-west1.gcp.commercetools.com/************/types' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer EyVFlBHo5XjRD6QdjEA***********' \
--data-raw '{
  "key" : "cart_abandoned_tag",
  "name" : {
    "en" : "cart_abandoned_tag"
  },
  "description" : {
    "en" : "Define the iteration tag of a cart defined abandoned"
  },
  "resourceTypeIds" : [ "order" ],
  "fieldDefinitions" : [ {
    "name" : "cart_abandoned_tag",
    "label" : {
      "en" : "cart_abandoned_tag"
    },
    "required" : false,
    "type" : {
      "name" : "Number"
    }
  } ]
}'
```

Then I set my custom field to a cart this way, it also works as expected
```
curl --location --request POST 'https://api.europe-west1.gcp.commercetools.com/************/carts/9cba350a-9a89-4bee-9b22-487e57bc999b' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer EyVFlBHo5XjRD6QdjEAp8r************' \
--data-raw '{
    "version": 13,
    "actions": [
        {
            "action" : "setCustomType",
            "type" : {
              "id" : "3259d348-441a-4067-b4dc-e5e8bedd6bfa",
              "typeId" : "type"
            },
            "fields" : {
              "cart_abandoned_tag" : 1
            }
          }
    ]
}'
```

But when I need to do it in C# (I use the 4.0.0 version of the CT client), it's not clear about what I'm supposed to use as an update action, indeed the Action field is a string, I supposed I need to push a serialized object :

```csharp
await _commerceToolsClient
                .WithApi().WithProjectKey(_projectKey)
                .Carts()
                .WithId(cartId)
                .Post(new CartUpdate
                {
                    Version = currentCart.Version,
                    Actions = new List<ICartUpdateAction> 
                    {
           new CartUpdateAction
            {
                Action = new
                {
                    action = "setCustomType",
                    type = new
                    {
                        id = abandonedFieldId,
                        typeId = "type"
                    },
                    fields = new
                    {
                        cart_abandoned_tag = abandonedTag
                    }
                }.Serialize()
                    }
                })
                .ExecuteAsync();
```

but it fails wit the error

```
[13:17:10 ERR] An unhandled exception has occurred while executing the request.
commercetools.Base.Client.Error.BadRequestException: Client error response https://api.europe-west1.gcp.commercetools.com/*****************/carts/9cba350a-9a89-4bee-9b22-487e57bc999b 400 Bad Request
   at commercetools.Base.Client.ErrorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at commercetools.Base.Client.Middlewares.HttpMiddleware.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at commercetools.Base.Client.Middlewares.AuthorizationMiddleware.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at commercetools.Base.Client.Middlewares.CorrelationIdMiddleware.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at commercetools.Base.Client.CtpClient.ExecuteAsJsonAsync(HttpRequestMessage requestMessage)
   at commercetools.Base.Client.CtpClient.ExecuteAsync[T](HttpRequestMessage requestMessage)
   at commercetools.Sdk.Api.Client.RequestBuilders.Carts.ByProjectKeyCartsByIDPost.ExecuteAsync()
```

**Comment by jenschude** [comment]
You can use the CartSetCustomTypeAction:

```
           this._projectApiRoot = serviceProviderFixture.GetService<ProjectApiRoot>();

            await _projectApiRoot
                .Carts()
                .WithId("cartId")
                .Post(new CartUpdate
                {
                    Version = 1,
                    Actions =
                    {
                        new CartSetCustomTypeAction
                        {
                            Type =
                            {
                                Id = "abandonedFieldId"
                            },
                            Fields =
                            {
                                { "id", "abandonedTag" }
                            }
                        }
                    }
                })
                .ExecuteAsync();
```

I would also suggest that you use the projectApiRoot to avoid injecting the projectKey at every request.

**Comment by NicolasREY69330** [comment]
Hello @jenschude 

When I perform the query you suggest (with projectApiRoot  or with the standard commerceToolsClient),

```csharp
                await _commerceToolsClient
                    .WithApi().WithProjectKey(_projectKey)
                    .Carts()
                    .WithId("bda0b57b-024a-4cde-98af-a43594ded4c8")
                    .Post(new CartUpdate
                    {
                        Version = 4,
                        Actions =
                        {
                            new CartSetCustomTypeAction
                            {
                                Type =
                                {
                                    Id = "3259d348-441a-4067-b4dc-e5e8bedd6bfa"
                                },
                                Fields =
                                {
                                    { "cart_abandoned_tag", 2 }
                                }
                            }
                        }
                    })
                    .ExecuteAsync();
```

I get the error :
```
Exception thrown: 'System.NullReferenceException' in IT.Microservices.AbandonedCartDetector.dll: 'Object reference not set to an instance of an object.'
```
I suspect the `Type `or `Fields `properties to be the root cause, but I require your help again.

BWT : is using projectApiRoot  instead commerceToolsClient is for DI convenience only ? I mean there is no impact on performance right ?

Thank you

**Comment by jenschude** [comment]
Ah sorry. My fault with to much juggling between languages:

```
            await projectApiRoot
                .Carts()
                .WithId("bda0b57b-024a-4cde-98af-a43594ded4c8")
                .Post(new CartUpdate
                {
                    Version = 4,
                    Actions = new List<ICartUpdateAction>()
                    {
                        new CartSetCustomTypeAction
                        {
                            Type = new TypeResourceIdentifier()
                            {
                                Id = "3259d348-441a-4067-b4dc-e5e8bedd6bfa"
                            },
                            Fields = new FieldContainer()
                            {
                                { "cart_abandoned_tag", 2 }
                            }
                        }
                    }
                })
                .ExecuteAsync();
```

The types should be correctly stated.

And yes the projectApiRoot is a convenience class. There should be no performance impact.

**Comment by NicolasREY69330** [comment]
Perfect it works like a charm, thank you
