### ISSUE TITLE
No Blazor WASM support

### ISSUE THREAD

**Issue by CollinAlpert** [commercetools/commercetools-dotnet-core-sdk-v2#206]
**Describe the bug**
When adding the Commerce Tools SDK to a Blazor WASM application via the `UseCommerceToolsApi` extension method, it throws a `PlatformNotSupportedException` due to the `HttpClientHandler.AutomaticDecompression` being set ([see here](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs#L107))

**To Reproduce**
Add the Commerce Tools SDK via the `UseCommerceToolsApi` extension method to a Blazor WASM application.

**Expected behavior**
The API client is added and can be used without issues.

**Stack trace**
```
Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
   at commercetools.Base.Client.DependencyInjectionSetup.<>c.<SetupClient>b__4_1(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass3_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
```

**Stack information:**
 - .NET 7 (Microsoft.NET.Sdk.BlazorWebAssembly)
 - Package version: 6.1.0

**Additional context:**
The `AutomaticDecompression` property is not supported in Blazor WASM ([see here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L85)). Maybe it would be a good idea to allow the configuration of this in the `UseCommerceToolsApi` extension method or to allow the SDK to be constructed in a way to work around this limitation.

**Comment by jenschude** [comment]
The decompression is actually quite important as the returned results could be quite big and the transfer time will impact the performance.

Nevertheless we will investigate how to make it configurable.

**Comment by CollinAlpert** [comment]
Thanks!

**Comment by jenschude** [comment]
The UseCommercetoolsApi method now has a parameter for ClientOptions. Which allow to set the Compression methods to be used.

**Comment by CollinAlpert** [comment]
Great, thanks!
